version: '3'
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: jrebel
    container_name: jrebel
    restart: 'always'
    ports:
      - "800:800"
    deploy:
      placement:
        constraints: [node.hostname == qcloud]
    networks:
      - network
networks:
  network:
    driver: overlay