version: '3.8'
services:
  kafka1:
    image: kafka:v2.11-2.4.1
    environment:
      - JAVA_HOME=/usr
    volumes:
      - hadoop-opt:/opt
    privileged: true
    hostname: kafka1
    container_name: kafka1
    ports:
      - 9092:9092
    networks:
      - hadoop
  kafka2:
    image: kafka:v2.11-2.4.1
    environment:
      - JAVA_HOME=/usr
    volumes:
      - hadoop-opt:/opt
    privileged: true
    hostname: kafka2
    container_name: kafka2
    ports:
      - 9093:9092
    networks:
      - hadoop
networks:
  hadoop: {
    external: true
  }
volumes:
  hadoop-opt: {
    external: true
  }
