apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs
  namespace: default
spec:
  # 副本扩容
  # kubectl scale deployment deploy-nginx --replicas=3
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: c1
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80