apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds
  namespace: default
spec:
  # 副本扩容
  # kubectl scale deployment deploy-nginx --replicas=3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations: # tolerations代表容忍
        - key: node-role.kubernetes.io/master  # 能容忍的污点key
          effect: NoSchedule   # kubectl explain pod.spec.tolerations查看(能容忍的污点effect)
      containers:
        - name: c1
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80