apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
  namespace: default
spec:
  schedule: "*/1 * * * *" # 每分钟执行一次
  jobTemplate:
    spec:
      template:
        metadata:
          name: job1
        spec:
          restartPolicy: Never
          containers:
            - name: c1
              image: busybox
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh", "-c", "echo hello; sleep 10"]