apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: default
spec:
  clusterIP: None
  selector:
    app: sts-nginx
  ports:
    - port: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-nginx
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sts-nginx
  serviceName: svc-nginx
  template:
    metadata:
      labels:
        app: sts-nginx
    spec:
      containers:
        - name: c1
          image: nginx
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: www
      volumes:
        - name: www
          hostPath:
            path: /opt/www
            