#需求先安装MetalLB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-nginx-loadbalancer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc-nginx-loadbalancer
  template:
     metadata:
       labels:
         app: svc-nginx-loadbalancer
     spec:
       containers:
       - name: c1
         image: nginx:1.15-alpine
         imagePullPolicy: IfNotPresent
         ports:
         - containerPort: 80

### kubectl expose deployment deploy-nginx --type=ClusterIP --target-port=80 --port=80

---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30002
  selector:
    app: svc-nginx-loadbalancer