apiVersion: v1
kind: Pod
metadata:
  name: vol-hostpath
spec:
  containers:
    - name: vol-hostpath
      image: nginx:1.15-alpine
      imagePullPolicy: IfNotPresent
      command: ["sh","-c","echo haha > /data/1.txt ; sleep 6000"]
      volumeMounts:
        - name: vol-hostpath
          mountPath: /data
  volumes:
    - name: vol-hostpath
      hostPath:
        path: /tmp/vol-hostpath
        type: DirectoryOrCreate