apiVersion: v1
kind: Pod
metadata:
  name: vol-emptydir
spec:
  containers:
    - name: vol-emptydir1
      image: nginx:1.15-alpine
      imagePullPolicy: IfNotPresent
      command: ["sh","-c","echo haha > /data/1.txt ; sleep 6000"]
      volumeMounts:
        - name: vol-emptydir
          mountPath: /data
    - name: vol-emptydir2
      image: nginx:1.15-alpine
      imagePullPolicy: IfNotPresent
      command: ["sh","-c","cat /data/1.txt; sleep 6000"]
      volumeMounts:
        - mountPath: /data
          name: vol-emptydir
  volumes:
    - name: vol-emptydir
      emptyDir: {}