# ======================== Elasticsearch Configuration =========================
cluster.name: es-cluster
node.name: tribe
node.master: false
node.data: false
node.attr.rack: r1 
#bootstrap.memory_lock: true
http.port: 9204
transport.tcp.port: 9304
network.host: 0.0.0.0
discovery.seed_hosts: ["es-master:9300","es-data01:9301","es-data02:9302","es-data03:9303"]
cluster.initial_master_nodes: ["master"] 
gateway.recover_after_nodes: 2
