version: '3.8'
services:
  impala-master:
    image: impala:v2.7.5
    environment:
      - JAVA_HOME=/usr
    volumes:
      - hadoop-opt:/opt
      - impala-master-data:/data
    hostname: impala-master
    container_name: impala-master
    networks:
      - hadoop
    depends_on:
      - impala-slave1
  impala-slave1:
    image: impala:${HADOOP_VERSION}
    environment:
      - JAVA_HOME=/usr
    volumes:
      - hadoop-opt:/opt
      - impala-slave1-data:/data
    hostname: impala-slave1
    container_name: impala-slave1
    networks:
      - hadoop
networks:
  hadoop: {
    external: true
  }
volumes:
  hadoop-opt: {
    external: true
  }
  impala-master-data: {
    name: impala-master-data
  }
  impala-slave1-data: {
    name: impala-slave1-data
  }
