version: "3"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:latest
    ports:
      - "8848:8848"
      - "9555:9555"
    env_file:
      - env/nacos-embedded.env
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == aliyun]
  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:latest
    container_name: nacos2
    ports:
      - "8849:8848"
    env_file:
      - env/nacos-embedded.env
    restart: always
    deploy:
      placement:
        constraints: [node.hostname == qcloud]

