version: '3.8'
services:
  cdh6:
    build: ./build-support
    hostname: cdh6
    container_name: cdh6
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro #使用systemctl
    networks:
      - hadoop
    depends_on:
      - yum-cdh6
  yum-cdh6:
    image: nginx
    volumes:
      - /root/cdh6.3.2:/usr/share/nginx/html/cdh6.3.2
      - /root/cdh6.3.2/cm6.3.1:/usr/share/nginx/html/cm6.3.1
    hostname: yum-cdh6
    container_name: yum-cdh6
    privileged: true
    networks:
      - hadoop
networks:
  hadoop: {
    external: true
  }