version: '3.8'
services:
  spark_master:
    image: hadoop:v2.7.5
    environment:
      - JAVA_HOME=/usr
    volumes:
      - hadoop_opt:/opt
      - spark_master_data:/data
    privileged: true
    hostname: master
    ports:
      - 6066:6066
      - 7077:7077
      - 8080:8080
      - 9000:9000
      - 19888:19888
    networks:
      - hadoop
    depends_on:
      - spark_slave1
  spark_slave1:
    image: hadoop:v2.7.5
    environment:
      - JAVA_HOME=/usr
    volumes:
      - hadoop_opt:/opt
      - spark_slave1_data:/data
    privileged: true
    hostname: spark_slave1
    networks:
      - hadoop
networks:
  hadoop: {
    external: true
  }
volumes:
  hadoop_opt: {
    external: true
  }
  spark_master_data:
  spark_slave1_data:
