version: '3.8'
services:
  spark-master:
    image: spark:v2.2.0
    environment:
      - JAVA_HOME=/usr
    volumes:
      - hadoop-opt:/opt
      - spark-master-data:/data
    privileged: true
    hostname: spark-master
    container_name: spark-master
    ports:
      - 8080:8080
    networks:
      - hadoop
    depends_on:
      - spark-slave1
  spark-slave1:
    image: spark:v2.2.0
    environment:
      - JAVA_HOME=/usr
    volumes:
      - hadoop-opt:/opt
      - spark-slave1-data:/data
    privileged: true
    hostname: spark-slave1
    container_name: spark-slave1
    networks:
      - hadoop
networks:
  hadoop: {
    external: true
  }
volumes:
  hadoop-opt: {
    external: true
  }
  spark-master-data: {
    name: spark-master-data
  }
  spark-slave1-data: {
    name: spark-slave1-data
  }
