# ======================== Elasticsearch Configuration =========================
cluster.name: es-cluster
node.name: master 
node.master: true
node.data: false
node.attr.rack: r1 
#bootstrap.memory_lock: true
http.port: 9200
network.host: 0.0.0.0
transport.tcp.port: 9300
discovery.seed_hosts: ["es-master:9300","es-data01:9301","es-data02:9302","es-data03:9303","es-data03:9304"]
cluster.initial_master_nodes: ["master"]
gateway.recover_after_nodes: 2
