version: '3.8'
services:
  master:
    image: hadoop:v2.7.5
    environment:
      - JAVA_HOME=/usr
    volumes:
      - hadoop_opt:/opt
      - master_data:/data
    privileged: true
    hostname: master
    ports:
      - 8088:8088
      - 50070:50070
    networks:
      hadoop:
          ipv4_address: 172.18.0.2
    depends_on:
      - slave1
  slave1:
    image: hadoop:v2.7.5
    environment:
      - JAVA_HOME=/usr
    volumes:
      - hadoop_opt:/opt
      - slave1_data:/data
    privileged: true
    hostname: slave1
    networks:
      hadoop:
          ipv4_address: 172.18.0.3 #由于ip不固定，slave1删除失败的时候，多个slave1会出现多ip导致ssh失败
networks:
  hadoop: {
    external: true
  }
volumes:
  hadoop_opt: {
    external: true
  }
  master_data:
  slave1_data:
