version: '3.8'
services:
  master:
    image: hadoop:v2.7.5
    environment:
      - JAVA_HOME=/usr
    volumes:
      - hadoop-opt:/opt
    privileged: true
    hostname: master
    networks:
      - hadoop
    depends_on:
      - slave1
  slave1:
    image: hadoop:v2.7.5
    environment:
      - JAVA_HOME=/usr
    volumes:
      - hadoop-opt:/opt
    privileged: true
    hostname: slave1
    networks:
      - hadoop
networks:
  hadoop: {
    external: true
  }
volumes:
  hadoop-opt: {
    external: true
  }
