version: '3'
services:
  master:
    image: hadoop:v2.7.5
    volumes:
      - hadoop-opt:/opt
    networks:
      - hadoop
    privileged: true
  slave1:
    image: hadoop:v2.7.5
    volumes:
      - hadoop-opt:/opt
    networks:
      - hadoop
    privileged: true
    depends_on:
      - master
networks:
  hadoop: {
    external: true
  }
volumes:
  tools: {
    external: true
  }
  hadoop-opt: {
    external: true
  }
