apiVersion: v1
kind: Service
metadata:
  name: http-svc
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
      nodePort: 8081
  selector:
    app: nginx-deployment