version: '3.8'
services:
  hadoop-master:
    image: hadoop:v3.1.3
    environment:
      - JAVA_HOME=/usr
      - HADOOP_HOME=/opt/hadoop-3.1.3
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
      - YARN_RESOURCEMANAGER_USER=root
      - YARN_NODEMANAGER_USER=root
    volumes:
      - hadoop-opt:/opt
      - hadoop-master-data:/data
    privileged: true
    hostname: hadoop-master
    container_name: hadoop-master
    ports:
      - 8088:8088
      - 9000:9000
      - 19888:19888
      - 9870:9870
      - 9864:9864
      - 9866:9866
    networks:
      hadoop:
          ipv4_address: 172.18.0.100
    depends_on:
      - hadoop-slave1
  hadoop-slave1:
    image: hadoop:v3.1.3
    environment:
      - JAVA_HOME=/usr
    ports:
      - 50075:50075
      - 50010:50010
    volumes:
      - hadoop-opt:/opt
      - hadoop-slave1-data:/data
    privileged: true
    hostname: hadoop-slave1
    container_name: hadoop-slave1
    networks:
      hadoop:
          ipv4_address: 172.18.0.101 #由于ip不固定，slave1删除失败的时候，多个slave1会出现多ip导致ssh失败
networks:
  hadoop: {
    external: true
  }
volumes:
  hadoop-opt: {
    external: true
  }
  hadoop-master-data: {
    name: hadoop-master-data
  }
  hadoop-slave1-data: {
    name: hadoop-slave1-data
  }
