version: '3'
services:
  main:
    image: redis:6.0.6
    environment:
      - REDIS_PASSWORD=Welge@redis
    entrypoint: bash -c "echo requirepass $${REDIS_PASSWORD} > /etc/redis.conf && redis-server /etc/redis.conf"
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.hostname == ctyun]